api_hash: your_api_hash
api_id: your_api_id
chat:
- chat_id: telegram_chat_id
  last_read_message_id: 0
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
# 新增监控配置
monitor:
  enabled: true
  webhook_url: "https://discord.com/api/webhooks/你的URL"
  min_interval: 5
  window_sec: 300  # 监控窗口，默认5分钟
  startup_scan_window_sec: 21600   # 启动后回扫频道内消息范围6小时，config只支持改大，改小需要修改主程序
  startup_scan_sleep_sec: 0.3      # 每页之间 sleep，防止触发限流，config只支持改大，改小需要修改主程序
  startup_scan_page_size: 100      # 每次 GetHistory 拉多少（pyrogram这边最大常见是100），config只支持改大，改小需要修改主程序
  keywords:
  - 里番 #示例
  chats:
    #- -1001234567890
    #- -1009876543210
   - -1003050259377 #频道编号，可以通过发送给bot/get_info link查询，示例/get_info t.me/channel_name，支持同时监控多个频道
